---
title: "Where Do You Like A Cup of Safe Coffee?"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    source: embed
    code_folding: hide
    theme: flatly
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(leaflet)
library(shiny)
library(httr)
library(rvest)
library(sf)
library(shinyWidgets)

knitr::opts_chunk$set(
  message = F,
  echo = F,
  warning = F
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis",
  digits = 10
)

scale_colour_discrete = scale_colour_viridis_d

scale_fill_discrete = scale_fill_viridis_d

get_location =
  function(location_name = "Columbia University",
           .pd = NA) {
    if (!is.na(.pd)) {
      .pd$tick()$print()
    }
    
    location_name = str_c(
      "https://geosearch.planninglabs.nyc/v1/search?text=",
      location_name,
      ", New York, NY&size=2"
    )
    
    url =
      URLencode(location_name)
    
    df = read_sf(GET(url) %>% content("text"))
    
    if (nrow(df) == 0) {
      return(tibble(
        long = NA,
        lat = NA,
        borough = NA
      ))
    }
    
    geometry = df %>%
      pull(geometry) %>%
      as.tibble() %>%
      mutate(geometry = as.character(geometry),
             geometry = str_replace_all(geometry, "c|[\\(\\)]", "")) %>%
      separate(geometry, into = c("long", "lat"), sep = ",") %>%
      mutate_all(as.numeric) %>%
      summarise(long = mean(long),
                lat = mean(lat))
    return(geometry)
  }

```

```{r data}
if (file.exists("data/map_data.csv")){
  cafe = read_csv(here::here("data/map_data.csv"))
} else {source("map_data.R")}

now = lubridate::now("EST")
now_day = weekdays(now)
now_hour = lubridate::hour(now)

cafe = cafe %>% 
  filter(weekday == now_day,hour == now_hour) %>% 
  mutate(n_risk = forcats::fct_relevel(n_risk,
                                       "almost safe",
                                       "some risk",
                                       "BURNING RISKY"))
```

Options {.sidebar}
-----------------------------------------------------------------------

```{r Sidebar}
textInput(
  inputId = "location",
  label = h3("Where You At?"),
  value = "Columbia University"
)

sliderTextInput(
  inputId = "tolerant",
  label = h3("Risk Willing to take"),
  choice = c("almost safe",
             "some risk",
             "BURNING RISKY"),
  selected =
    "almost safe"
)

boro = cafe %>% distinct(borough) %>% pull(borough)

checkboxGroupInput(
  "borough",
  label = h3("Which Borough?"),
  choices = boro,
  selected = "Manhattan"
)


```

```{r,eval=F}
renderPrint({
  knitr::knit_print(now)
})
```



Row {data-width=1000}
-----------------------------------------------------------------------

### Cafe Map

```{r map}
pal = colorNumeric(
  palette = c("viridis", "magma", "inferno", "plasma")[[4]],
  domain = cafe$ticket %>% sqrt()
)

renderLeaflet({
    if (!is.null(input$location)) {
    locat = get_location(input$location)
    } else {locat = get_location()}
  
  
  plot_cafe_map =
    cafe  %>%
    filter(as.integer(n_risk)<=which(input$tolerant==levels(n_risk)),
           borough %in% input$borough)%>%
    mutate(pop =
             str_c("<h4>", business_name, "</h4>",
                   adress,"<br>",
                   swc_chairs," chairs in ",swc_sq_ft," feet space<br>",
                   "<h5>",n_risk,"</h5><b>",
                   hour_day_risk," ticket at ",
                   now_day,now_hour,":00 </b>out of <br>total<b>",
                   round(ticket), " tickets in 100m<br>",
                   "EXPECTED FINE AMOUNT : ",round(fine_amount,2),"$</b><br>",
                   sep = " ")) %>%
    select(long,lat,pop,business_name,ticket) %>% 
    leaflet() %>%
    addProviderTiles(providers$CartoDB.Positron) %>%
    addCircles(
      locat[[1]],
      locat[[2]],
      radius = 1000,
      label = "Your Location",
      weight = 1,
      fillOpacity = 0.5,
      group = "Nearby Cafe"
    ) %>% 
    addCircleMarkers(
      ~ long,
      ~ lat,
      color = ~ pal(ticket %>% sqrt()),
      radius = .1,
      popup = ~ (pop),
      label = ~str_c(business_name," <- CLICK"),
      group = "Cafe Shop"
    ) %>% 
    addLayersControl(
      overlayGroups = c("Nearby Cafe","Cafe Shop"),
      options = layersControlOptions(collapsed = FALSE)
    ) %>% 
    setView(lng = locat[[1]], lat = locat[[2]], zoom = 12)
  
  plot_cafe_map
})
  
```


```{r time,eval=F}
plot_time_df =
  cafe %>% 
  unnest(nearby) %>% 
  mutate(hour = lubridate::hour(issue_date),
         weekday = weekdays(issue_date),
         weekday = 
           forcats::fct_relevel(weekday,c("Monday","Tuesday","Wednesday",
               "Thursday","Friday","Saturday","Sunday"))) %>% 
  drop_na(borough) %>%
  count(weekday, hour, borough, name = "ticket") %>%
  mutate(text = str_c("TIME: ", hour, ":00 on ", weekday, 
                      "<br>Total Tickets:",ticket))
plot_time =
  plot_time_df %>% 
  plot_ly(
    type = "bar",
    x = ~ hour,
    y = ~ ticket,
    text = ~text,
    frame = ~ weekday,
    color = ~ borough,
    colors = viridis::viridis(4,option = "D")
  ) %>%
  layout(barmode = 'group',
         title = "Total Number of Tickets by Hour",
         showlegend = T,
         legend = list(orientation = "h"),
         yaxis =list(type = "log",
                     title = ''),
         xaxis = list(nticks = 24)) %>%
  animation_opts(transition = 0) %>% 
  animation_button(hide =T)
 
plot_time
```

